module.exports = {
  UBER_CLIENT_ID: '9lpXdwxyWAOB7k-aFLyGMrSq9xh0nwsc',
  UBER_SERVER_TOKEN: 'TYRruM8cTWQ_psRblwm3sDvNTLstgMdPIFN6ZHuG',
  UBER_SECRET: 'gKopK_--OwbG6cTbJRvQjx_AO4Btu5Ng4uD1zkh2',
  YELP_CONSUMER_KEY: '03heJf7mV1Sw7x3OtqD8lw',
  YELP_CONSUMER_SECRET: 'HA5m8NWSBjvKKKSyQm2yI3PpUPY',
  YELP_TOKEN: 'RV6VO_xEJ_wl02eebJ8MW2rGM_BLdeU5',
  YELP_TOKEN_SECRET: 'HcRblMbtBPjfvCKMMcy8V3QntBo',
  WIT_KEY: 'VWFMUGFTFVETAVWJGLEDTROOVGDI3TYX'
};