module.exports = {
  UBER_CLIENT_ID: process.env.HEROKU_UBER_CLIENT_ID || '9lpXdwxyWAOB7k-aFLyGMrSq9xh0nwsc',
  UBER_SERVER_TOKEN: process.env.HEROKU_SERVER_TOKEN || 'TYRruM8cTWQ_psRblwm3sDvNTLstgMdPIFN6ZHuG',
  UBER_SECRET: process.env.HEROKU_UBER_SECRET || 'gKopK_--OwbG6cTbJRvQjx_AO4Btu5Ng4uD1zkh2',
  WIT_KEY: process.env.HEROKU_WIT_KEY || 'VWFMUGFTFVETAVWJGLEDTROOVGDI3TYX'
};